### ISSUE TITLE
Migration from Webtrekk v4

### ISSUE THREAD

**Issue by mobru** [mapp-digital/MappIntelligence-iOS-v5#10]
Hi there,

I am currently in the process of migrating Webtrekk v4 to MappIntelligence v5, and have a few questions:
1. Is there automatic tracking in MappIntelligence v5 or not? I'm asking because I cannot find anything to disable it. And the documentation does at least mention automatic tracking (see [here](https://documentation.mapp.com/latest/en/default-parameters-19104055.html)) Also, `autoTracking: Bool` is part of the [configuration in the Android SDK](https://documentation.mapp.com/1.0/en/global-configuration-19103903.html).
2. What are the equivalents (and how / where to set them) for the configuration fields in webtrekk_config.xml file that was used in Webtrekk v4 (see attached dummy config fil: [dummy-config.txt](https://github.com/mapp-digital/MappIntelligence-iOS-v5/files/14873095/dummy-config.txt))?  
I currently only found equivalents for `trackId`, and `trackDomain` (both used in `initWithConfiguration(_:onTrackdomain:)`).

**Comment by stellatores** [comment]
Hi @mobru,

regarding your questions:
1. There is no automated tracking available in our iOS SDK so there is no option to turn it off.
2. There is no option to remotely configure the SDKs at the moment so there is no external file to configure this. To install, initialise, and configure the SDK you can follow the steps as described here: https://documentation.mapp.com/latest/en/getting-started-19103963.html

Please note that it is crucial to set should migrate to "true" as described here: https://documentation.mapp.com/latest/en/migrate-from-ios-sdk-version-4-19104182.html Otherwise you might lose historical data as the SDK will create new users instead of migrating the existing ones.
